name: ApexGuard
main: com.apexguard.ApexGuardPlugin
version: 1.0.2
api-version: 1.13
softdepend: [ProtocolLib]
authors: ["ApexGuard Team"]
website: https://example.org
commands:
  apexguard:
    description: ApexGuard administration command
    usage: /<command> <subcommand>
    permission: apexguard.admin
  agstats:
    description: Show per-player ApexGuard stats
    usage: /<command> [player]
    permission: apexguard.admin
permissions:
  apexguard.admin:
    description: Allows use of ApexGuard admin commands
    default: op